import { MenuItem } from "./menu-types";
import imgChicken from "@/assets/chicken.jpeg";
import imgLamb from "@/assets/lamb.jpeg";
import imgPaneer from "@/assets/paneer.jpeg";
import imgGoat from "@/assets/goat-cubes.jpeg";
import imgSoya from "@/assets/soya-chaap.jpeg";

export const proteinCubeSkewerPlatters: MenuItem[] = [
  {
    id: 1,
    name: "Signature Chicken Breast Platter",
    description: "Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad.",
    image: imgChicken,
    category: "Skewer Platter",
    heatLevel: 2,
    isPopular: true,
    addOns: ["Extra Chicken Skewer 4.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 11.99,
  },
  {
    id: 2,
    name: "Signature Lamb Platter",
    description: "Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad.",
    image: imgLamb,
    category: "Skewer Platter",
    heatLevel: 3,
    isPopular: true,
    addOns: ["Extra Lamb Skewer 5.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 13.99,
  },
  {
    id: 3,
    name: "Signature Goat Platter",
    description: "Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad.",
    image: imgGoat,
    category: "Skewer Platter",
    heatLevel: 3,
    isPopular: true,
    addOns: ["Extra Goat Skewer 5.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 13.99,
  },
  {
    id: 4,
    name: "Signature Soft Cheese Platter",
    description: "Indian Cheese Cubes. Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad.",
    image: imgPaneer,
    category: "Skewer Platter",
    heatLevel: 1,
    isPopular: false,
    addOns: ["Extra Paneer Skewer 3.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["milk"],
    dietary: ["vegetarian", "gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 9.99,
  },
  {
    id: 5,
    name: "Signature Soya Platter",
    description: "Plant-Based Cubes. Variation: 100G|200G|300G Protein. Served with Seasoned Rice and Salad.",
    image: imgSoya,
    category: "Skewer Platter",
    heatLevel: 2,
    isPopular: false,
    addOns: ["Extra Soya Skewer 3.99"],
    saucePairings: [],
    customizations: [],
    allergens: ["soy"],
    dietary: ["vegan", "gluten-free", "nut-free"],
    sidePairings: ["Cucumber Tomato", "Pickled Onion", "Sweet Corn & Pepper", "Lazzat Bean Salad"],
    price: 9.99,
  },
];
